"""
Django settings for hotelrecsys project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = '1!7o$)e_9(1^fln4pg^7orwpfn@jz)_mq54%9&nx5y0)ntoqun'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'app',
    'rest_framework',
    'channels',
    'corsheaders',
    'storages',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_seed',
    'django_filters',
    'background_task',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'app.utils.security.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'app.exceptions.exception_handler.exception_handler',
}

ROOT_URLCONF = 'hotelrecsys.urls'

PROJECT_NAME = 'hotelrecsys'

CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(BASE_DIR), 'app', 'utils', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotelrecsys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_ROOT = os.path.join(BASE_DIR, 'public')

MEDIA_URL = '/public/'

LANGUAGES = [
    ('en', _('English')),
    ('vi', _('Vietnamese')),
]

LOCALE_PATHS = [os.path.join(BASE_DIR, 'lang')]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ASGI_APPLICATION = "hotelrecsys.asgi.application"

CHANNEL_LAYERS = {
    'default': {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    },
}

STRIPE_PUBLISHABLE_KEY = 'pk_test_51ItvFvFGVTjHBXQ5Eihr6KmSi4FBceDHhDSGTOwKoNyVoeB39N5YIxtOk5E8ylWNm9j4CkrzQWOQ4nnSNMo7gp8X00SrcmAzBy'
STRIPE_SECRET_KEY = 'sk_test_51ItvFvFGVTjHBXQ5DIrdwer1x4EmNvkto0tjJoxhKyyIyhzBcnv1kp7fR4KwVsY6ciFDzAA3epAKeLft2IVzRJTM00m2WXYvP5'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
AUTH_USER_MODEL = 'app.User'
ENCRYPTION_ALGORITHM = 'HS256'
DEFAULT_COUNTRY_CODE = 'VN'
EMAIL_FROM_NAME = os.environ.get('EMAILS_FROM_NAME')
EMAIL_FROM_EMAIL = os.environ.get('EMAILS_FROM_EMAIL')
SMTP_HOST = os.environ.setdefault('SMTP_HOST', 'smtp.gmail.com')
SMTP_PORT = os.environ.setdefault('SMTP_PORT', '587')
SMTP_TLS = os.environ.get('SMTP_TLS', True)
SMTP_USER = os.environ.get('SMTP_USER')
SMTP_PASSWORD = os.environ.get('SMTP_PASSWORD')
TOKEN_EXPIRED_AFTER_MINUTES = 1440
CHAR_FIELD_MAX_LEN = 32768
TEL_LEN = 10
AREA_FIELD_MAX_LEN = 65536

DEBUG = True

SECRET_KEY = '1!7o$)e_9(1^fln4pg^7orwpfn@jz)_mq54%9&nx5y0)ntoqun'

LOG_FILE = f'/tmp/backend.log'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOG_FILE,
            'mode': 'a+',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.setdefault('DB_HOST', 'localhost'),
        'USER': os.environ.setdefault('DB_USER', 'tiendung'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '123456'),
        'NAME': os.environ.setdefault('DB_NAME', 'hotelrecsys')
    },
    'recsys': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.setdefault('DB_HOST', 'localhost'),
        'USER': os.environ.setdefault('DB_USER', 'tiendung'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'NAME': os.environ.setdefault('DB_NAME', 'recsys')
    },
}

SERVER_HOST = 'localhost:8000'

DEFAULT_FILE_STORAGE = 'app.utils.storage_backends.LocalStorage'

CORS_ORIGIN_ALLOW_ALL = True

IMAGE_SEED_FOLDER = os.environ.setdefault('IMAGE_SEED_FOLDER', f'/home/{os.environ.get("USER")}/Downloads/images')
